APPLICATION_NAME = "Zup"
APPLICATION_AUTHOR = "jof"

DEFAULT_CLICKUP_LISTS: list[str] = []

DEFAULT_SCHEDULE_TYPE = "schedule"
DEFAULT_SCHEDULE_LIST = ["06:00", "11:00", "14:00"]
DEFAULT_INTERVAL_HOURS = 0
DEFAULT_INTERVAL_MINUTES = 15
